name: build and deploy
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Test and Build React App
      run: |
        cd ./client
        npm install
        npm run build

    - name: Login into container registry
      run: |
        az acr login --name ${{ secrets.CONTAINER_REGISTRY_NAME }}

    - name: Build and push docker image (nginx-reverse-proxy)
      run: |
       cd ./nginx/production
       docker image build -t ${{ secrets.CONTAINER_REGISTRY_NAME }}/nginx-react-image:latest .
       docker push ${{ secrets.CONTAINER_REGISTRY_NAME }}/nginx-react-image:latest

    - name: Build and push docker image (fastapi)
      run: |
       cd ./server
       docker image build -t ${{ secrets.CONTAINER_REGISTRY_NAME }}/fastapi-image:latest .
       docker push ${{ secrets.CONTAINER_REGISTRY_NAME }}/fastapi-image:latest

    - name: Set connection string
      run: |
       az webapp config appsettings set -g ${{ secrets.RESOURCE_GROUP_NAME }} -n test-app-container --settings MONGODB_URL="${{ secrets.MONGODB_URL }}"

    - name: Deploy with docker-compose
      run: |
       az webapp config container set --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name test-app-container --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml

