name: build and deploy
on:
  push:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Test and Build React App
      run: |
        cd ./client
        npm install
        npm run test
        npm run build
    
    - name: Test working dir
      run: |
        pwd
    



